export const userActionTypes = {
    LOGGED_IN_USER : "LOGGED_IN_USER",
    LOGOUT : "LOGOUT",
    USER_LOADING : "USER_LOADING",
    USER_LOADING_DONE : "USER_LOADING_DONE"
}

export const categoryActionTypes = {
    CATEGORY_LOADING : "CATEGORY_LOADING",
    CATEGORY_LOADING_DONE : "CATEGORY_LOADING_DONE",
    CREATE_CATEGORY : "CREATE_CATEGORY",
    UPDATE_CATEGORY : "UPDATE_CATEGORY",
    LIST_ALL_CATEGORY : "LIST_ALL_CATEGORY",
    REMOVE_CATEGORY : "REMOVE_CATEGORY",
    
}

export const subCategoryActionTypes = {
        SUBCATEGORY_LOADING : "SUBCATEGORY_LOADING",
        SUBCATEGORY_LOADING_DONE : "SUBCATEGORY_LOADING_DONE",
        CREATE_SUBCATEGORY : "CREATE_SUBCATEGORY",
        UPDATE_SUBCATEGORY : "UPDATE_SUBCATEGORY",
        LIST_ALL_SUBCATEGORY  : "LIST_ALL_SUBCATEGORY",
        REMOVE_SUBCATEGORY  : "REMOVE_SUBCATEGORY"
}