export const userActionTypes = {
    LOGGED_IN_USER : "LOGGED_IN_USER",
    LOGOUT : "LOGOUT",
    USER_LOADING : "USER_LOADING",
    USER_LOADING_DONE : "USER_LOADING_DONE"
}

export const categoryActionTypes = {
    CATEGORY_LOADING : "CATEGORY_LOADING",
    CATEGORY_LOADING_DONE : "CATEGORY_LOADING_DONE",
    CREATE_CATEGORY : "CREATE_CATEGORY",
    UPDATE_CATEGORY : "UPDATE_CATEGORY",
    LIST_ALL_CATEGORY : "LIST_ALL_CATEGORY",
    REMOVE_CATEGORY : "REMOVE_CATEGORY",
    
}